### ISSUE TITLE
Q: benefits of using std::this_thread::yield()?

### ISSUE THREAD

**Issue by angelskieglazki** [antkeeper/antkeeper#9]
Hello :hugs: 
Can you tell, what are the benefits of using the std::this_thread::yield function instead of the std::this_thread::sleep_for function in this context?
regards, max
```
		// Idle
		do
		{
			std::this_thread::yield();
			m_frame_end_time = clock_type::now();
		}
		while (m_frame_end_time < idle_time);
```

**Comment by cjhoward** [comment]
Hi, Max! This code caps the framerate if a minimum frame duration is set. I believe that `std::this_thread::sleep_for` will sleep for *at least* the given duration, but possibly longer, with some people reporting a 1ms minimum. `std::this_thread::yield` is similar to calling `sleep_for(0)`, but may have a smaller minimum duration. I wanted an accurate and stable framerate, so I went with `yield`. There is some interesting discussion about this [here](https://stackoverflow.com/questions/17325888/c11-thread-waiting-behaviour-stdthis-threadyield-vs-stdthis-thread).

`yield` might cause a 100% CPU load on a single core, so this code may be worth revisiting to implement an accurate yet efficient idle such as described [here](https://blat-blatnik.github.io/computerBear/making-accurate-sleep-function/).

**Comment by angelskieglazki** [comment]
Thank you so much!
